# Generated by Django 4.0.2 on 2023-02-28 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle - {self.year}, {make} {model}'},
        ),
    ]
