# Generated by Django 4.0.2 on 2023-03-23 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('AWAIT', 'Awaiting'), ('RENT', 'Rented'), ('DIS', 'Returned')], default='NYR', max_length=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
