# Generated by Django 4.0.2 on 2023-02-28 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0002_alter_vehicle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'verbose_name': 'Vehicle - {self.year}, {self.make} {self.model}'},
        ),
    ]
