# Generated by Django 4.0.2 on 2023-03-23 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0002_alter_manager_options_remove_vehicle_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('AWAIT', 'Awaiting'), ('RENT', 'Rented'), ('DIS', 'Returned')], default='AWAIT', max_length=10),
        ),
    ]
