# Generated by Django 4.1.6 on 2023-03-30 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0004_alter_reservation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
    ]
