# Generated by Django 4.0.2 on 2023-03-30 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0005_reservation_insurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
