# Generated by Django 4.1.6 on 2023-04-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0006_alter_reservation_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='photoFileName',
            field=models.CharField(default='', max_length=20),
        ),
    ]
