# Generated by Django 4.1.6 on 2023-03-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0006_remove_reservation_customer_reservation_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={},
        ),
    ]
