# Generated by Django 4.1.6 on 2023-04-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carRental', '0007_vehicle_photofilename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photoFileName',
            field=models.CharField(default='', max_length=35),
        ),
    ]
